/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function customize_symbol(a: number, b: number, c: number): void;
export function deriveComplianceScalarForAddress(a: number, b: number, c: number): void;
export function pocSignDevAssetRegistration(a: number, b: number, c: number): void;
export function pocBuildDevUserRegistration(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function pocOrbisAuditBundles(a: number, b: number, c: number): void;
export function authorize(a: number, b: number, c: number, d: number, e: number): void;
export function witness(a: number, b: number, c: number, d: number): void;
export function build_action_proof_request(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function build_action_with_proof_result(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number): void;
export function build_action(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function build_serial(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function build_parallel(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function __wbg_txpandtxvbytes_free(a: number, b: number): void;
export function __wbg_get_txpandtxvbytes_txp(a: number, b: number): void;
export function __wbg_set_txpandtxvbytes_txp(a: number, b: number, c: number): void;
export function __wbg_get_txpandtxvbytes_txv(a: number, b: number): void;
export function __wbg_set_txpandtxvbytes_txv(a: number, b: number, c: number): void;
export function transaction_perspective_and_view(a: number, b: number, c: number, d: number, e: number): number;
export function transaction_summary(a: number, b: number): number;
export function generate_spend_key(a: number, b: number, c: number): void;
export function get_full_viewing_key(a: number, b: number, c: number): void;
export function get_wallet_id(a: number, b: number, c: number): void;
export function get_address_by_index(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function get_ephemeral_address(a: number, b: number, c: number, d: number): void;
export function get_index_by_address(a: number, b: number, c: number, d: number, e: number): void;
export function is_controlled_address(a: number, b: number, c: number, d: number, e: number): void;
export function __wbg_forwardingaddrresponse_free(a: number, b: number): void;
export function __wbg_get_forwardingaddrresponse_noble_addr_bech32(a: number, b: number): void;
export function __wbg_set_forwardingaddrresponse_noble_addr_bech32(a: number, b: number, c: number): void;
export function __wbg_get_forwardingaddrresponse_noble_addr_bytes(a: number, b: number): void;
export function __wbg_set_forwardingaddrresponse_noble_addr_bytes(a: number, b: number, c: number): void;
export function __wbg_get_forwardingaddrresponse_shieldd_addr_bytes(a: number, b: number): void;
export function __wbg_set_forwardingaddrresponse_shieldd_addr_bytes(a: number, b: number, c: number): void;
export function get_noble_forwarding_addr(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function __wbg_transparentaddrresponse_free(a: number, b: number): void;
export function __wbg_get_transparentaddrresponse_address(a: number, b: number): void;
export function __wbg_get_transparentaddrresponse_encoding(a: number, b: number): void;
export function get_transparent_address(a: number, b: number, c: number): void;
export function get_transmission_key_by_address(a: number, b: number, c: number): void;
export function __wbg_set_transparentaddrresponse_address(a: number, b: number, c: number): void;
export function __wbg_set_transparentaddrresponse_encoding(a: number, b: number, c: number): void;
export function get_asset_id(a: number, b: number, c: number): void;
export function sct_position(a: number, b: number, c: number, d: number): void;
export function __wbg_viewserver_free(a: number, b: number): void;
export function viewserver_new(a: number, b: number, c: number, d: number): number;
export function viewserver_new_snapshot(a: number, b: number, c: number, d: number, e: number): number;
export function viewserver_scan_genesis_chunk(a: number, b: number, c: number, d: number, e: number): number;
export function viewserver_genesis_advice(a: number, b: number, c: number): number;
export function viewserver_scan_block(a: number, b: number, c: number, d: number): number;
export function viewserver_flush_updates(a: number, b: number): void;
export function viewserver_get_sct_root(a: number, b: number): void;
export function viewserver_is_controlled_address(a: number, b: number, c: number, d: number): void;
export function plan_transaction(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number, d: number): number;
export function __wbindgen_free(a: number, b: number, c: number): void;
export const __wbindgen_export_3: WebAssembly.Table;
export function _dyn_core__ops__function__Fn_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hf5795f46210c030d(a: number, b: number): void;
export function _dyn_core__ops__function__Fn__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hc708157ed3c5a902(a: number, b: number, c: number): void;
export function _dyn_core__ops__function__FnMut__A____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1f0c456e75ee6284(a: number, b: number, c: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_exn_store(a: number): void;
export function wasm_bindgen__convert__closures__invoke2_mut__h57af48eaa0d5870d(a: number, b: number, c: number, d: number): void;
