import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import {
  ArchiveRangeRequest,
  ArchiveRangeResponse,
  KeyValueResponse,
  KeyValueResponse_Value,
} from '@mizufinance/protobuf/shieldd/storage/v1/storage_pb';
import {
  Nullifier,
  NullifierResponse,
} from '@mizufinance/protobuf/shieldd/core/component/sct/v1/sct_pb';
import { verifyValue, verifyNullifier, verifyArchiveRange } from '../dist/native-proof.js';
import init from '../wasm/index.js';

// Generated by Shieldd's proof_consumers owning test with SHIELDD_PROOF_VECTORS.
const vectors = JSON.parse(await readFile(new URL('./native-proof-vectors.json', import.meta.url)));
const bytes = value => Uint8Array.from(value);
const anchor = bytes(vectors.anchor);
await init({ module_or_path: await readFile(new URL('../wasm/index_bg.wasm', import.meta.url)) });
const value = new KeyValueResponse({
  value: new KeyValueResponse_Value({ value: bytes(vectors.value) }),
  proof: bytes(vectors.present),
});
assert.deepEqual(
  await verifyValue(value, anchor, new TextDecoder().decode(bytes(vectors.key))),
  bytes(vectors.value),
);
assert.equal(
  await verifyValue(
    new KeyValueResponse({ proof: bytes(vectors.absent) }),
    anchor,
    new TextDecoder().decode(bytes(vectors.absentKey)),
  ),
  undefined,
);
const wrongAnchor = anchor.slice();
wrongAnchor[0] ^= 1;
await assert.rejects(verifyValue(value, wrongAnchor, new TextDecoder().decode(bytes(vectors.key))));
await assert.rejects(verifyValue(value, anchor, 'consumer/missing'));
value.value.value[0] ^= 1;
await assert.rejects(verifyValue(value, anchor, new TextDecoder().decode(bytes(vectors.key))));

const nullifier = bytes(vectors.nullifier);
const spent = new NullifierResponse({
  nullifier: new Nullifier({ inner: nullifier }),
  spent: true,
  proof: bytes(vectors.spent),
});
assert.equal(await verifyNullifier(spent, anchor, nullifier), true);
await assert.rejects(verifyNullifier(spent, wrongAnchor, nullifier));
const other = nullifier.slice();
other[0]++;
await assert.rejects(verifyNullifier(spent, anchor, other));
spent.spent = false;
await assert.rejects(verifyNullifier(spent, anchor, nullifier));

const query = new ArchiveRangeRequest({
  height: BigInt(vectors.query.height),
  prefix: bytes(vectors.query.prefix),
  start: bytes(vectors.query.start),
  limit: vectors.query.limit,
});
const range = new ArchiveRangeResponse({ proof: bytes(vectors.archive) });
const page = await verifyArchiveRange(range, anchor, query);
assert.deepEqual(
  page.records,
  vectors.page.records.map(({ key, value }) => ({ key: bytes(key), value: bytes(value) })),
);
assert.deepEqual(page.next, bytes(vectors.page.next));
await assert.rejects(verifyArchiveRange(range, wrongAnchor, query));
query.limit++;
await assert.rejects(verifyArchiveRange(range, anchor, query));
query.limit--;
range.proof = bytes([...vectors.archive, 0xa0, 6, 0]);
await assert.rejects(verifyArchiveRange(range, anchor, query));
console.log(
  'Shared native/WASM verification accepts anchored values, absence, spentness, and mid-history archive ranges; substitutions and noncanonical proofs fail.',
);
